#!/bin/sh
# Build the PRODUCTION LOCAL APP bundles for the Payroll tool.
#
#   macos/build_app.sh [--install] [--desktop] [output_dir]
#
#   --install   also copy the bundles into ~/Applications
#   --desktop   also place Desktop shortcuts (symlinks) next to the copy
#
# The bundles are thin launchers: no Electron, no Tauri, no rewritten UI.  Each
# bundle embeds the absolute checkout path and interpreter so double-clicking
# never depends on the shell cwd, a terminal window, or a temporary directory.
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)

INSTALL=0
DESKTOP=0
OUTPUT_DIR=""
for arg in "$@"; do
    case "$arg" in
        --install) INSTALL=1 ;;
        --desktop) DESKTOP=1 ;;
        -*) echo "未知参数：$arg" >&2; exit 2 ;;
        *) OUTPUT_DIR="$arg" ;;
    esac
done

if [ -z "$OUTPUT_DIR" ]; then
    OUTPUT_DIR="$REPO_ROOT/macos/dist"
fi

PYTHON="$REPO_ROOT/.venv/bin/python"
if [ ! -x "$PYTHON" ]; then
    PYTHON=$(command -v python3 || true)
fi
if [ -z "$PYTHON" ] || [ ! -x "$PYTHON" ]; then
    echo "找不到可用的 Python 解释器。" >&2
    exit 1
fi

if [ ! -f "$REPO_ROOT/payroll_ui/server.py" ]; then
    echo "找不到 payroll_ui，检查目录：$REPO_ROOT" >&2
    exit 1
fi

# A single quote in a path would break the generated shim; refuse instead of
# producing a silently broken bundle.
case "$REPO_ROOT$PYTHON" in
    *"'"*) echo "路径中包含单引号，无法生成启动器。" >&2; exit 1 ;;
esac

mkdir -p "$OUTPUT_DIR"

build_bundle() {
    bundle_name="$1"
    mode="$2"
    bundle_id="$3"
    bundle="$OUTPUT_DIR/$bundle_name.app"

    rm -rf "$bundle"
    mkdir -p "$bundle/Contents/MacOS" "$bundle/Contents/Resources"

    cat > "$bundle/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>$bundle_name</string>
    <key>CFBundleDisplayName</key>
    <string>$bundle_name</string>
    <key>CFBundleIdentifier</key>
    <string>$bundle_id</string>
    <key>CFBundleExecutable</key>
    <string>launcher</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>LSMinimumSystemVersion</key>
    <string>11.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST

    printf 'APPL????' > "$bundle/Contents/PkgInfo"

    cat > "$bundle/Contents/MacOS/launcher" <<SHIM
#!/bin/sh
# Generated by macos/build_app.sh - do not edit by hand.
# Re-run the builder if the checkout moves.
REPO_ROOT='$REPO_ROOT'
PYTHON='$PYTHON'
export PAYROLL_LAUNCHER_REPO_ROOT="\$REPO_ROOT"
export PAYROLL_LAUNCHER_PYTHON="\$PYTHON"
export PYTHONPATH="\$REPO_ROOT/tools:\$REPO_ROOT"
cd "\$REPO_ROOT" || exit 1
exec "\$PYTHON" -m payroll_launcher --mode $mode "\$@"
SHIM
    chmod +x "$bundle/Contents/MacOS/launcher"

    cat > "$bundle/Contents/Resources/launcher.json" <<JSON
{
  "contract": "payroll-launcher/1",
  "mode": "$mode",
  "repo_root": "$REPO_ROOT",
  "python": "$PYTHON",
  "port": 8760,
  "data_dir": "$HOME/Library/Application Support/EducationPayroll"
}
JSON

    # An unsigned local bundle is fine; clear any inherited quarantine flag.
    xattr -dr com.apple.quarantine "$bundle" 2>/dev/null || true
    echo "已生成：$bundle"
}

build_bundle "工资核算助手" "open" "com.renjie.education-payroll.launcher"
build_bundle "重启工资服务" "restart" "com.renjie.education-payroll.launcher-restart"

if [ "$INSTALL" = "1" ]; then
    TARGET="$HOME/Applications"
    mkdir -p "$TARGET"
    for name in "工资核算助手" "重启工资服务"; do
        rm -rf "$TARGET/$name.app"
        cp -R "$OUTPUT_DIR/$name.app" "$TARGET/$name.app"
        xattr -dr com.apple.quarantine "$TARGET/$name.app" 2>/dev/null || true
        echo "已安装：$TARGET/$name.app"
    done
    if [ "$DESKTOP" = "1" ]; then
        for name in "工资核算助手" "重启工资服务"; do
            ln -sfn "$TARGET/$name.app" "$HOME/Desktop/$name.app"
            echo "已放置桌面入口：$HOME/Desktop/$name.app"
        done
    fi
fi

echo
echo "本机路径："
echo "  正式入口     : $OUTPUT_DIR/工资核算助手.app"
echo "  安全重启入口 : $OUTPUT_DIR/重启工资服务.app"
[ "$INSTALL" = "1" ] && echo "  已安装到     : $HOME/Applications/"
echo "  固定端口     : 8760"
echo "  正式数据目录 : $HOME/Library/Application Support/EducationPayroll"
